[Tester]
Expert=ThreeDayTrendSignal\ThreeDayTrendSignalEA.ex5
Symbol=EURUSD
Period=H1

FromDate=2018.01.01
ToDate=2019.01.01

Model=4
Optimization=0
Visual=0

ExpertParameters=ThreeDayTrendSignal_WalkForward_Current.set
Report=reports\tdts_rm_2018_5y_1y_1y\oos\EURUSD_TDTS_Pass931_OOS_20180101_20190101.xml

; ForwardMode=2
; OptimizationCriterion=7

ShutdownTerminal=1
