[Tester]
Expert=WeekHighLow\WeekHighLowEA.ex5
Symbol=XCUUSD
Period=H1

FromDate=2012.01.01
ToDate=2018.01.01

Model=4
Optimization=0
Visual=0

ExpertParameters=ImpulseContinuation_FTMO_EURUSDGenetic_CrossSymbol_Current.set
Report=reports\ftmo_eurusd_d1_stoploss_split_genetic_20260617\cross_symbol_is_val\XCUUSD_D1StopLossSplit_FTMOEURUSD_Pass625_VAL_20120101_20180101.xml

; ForwardMode=2
; OptimizationCriterion=7

ShutdownTerminal=1
