[Tester]
Expert=WeekHighLow\WeekHighLowEA.ex5
Symbol=GBPCHF
Period=H1

FromDate=2000.01.01
ToDate=2012.01.01

Model=4
Optimization=0
Visual=0

ExpertParameters=ImpulseContinuation.set
Report=reports\GBPCHF_2000_2012_ImpulseContinuation.xml

; ForwardMode=2
; OptimizationCriterion=7

ShutdownTerminal=1
