param(
  [string]$CandidateCsv = (Join-Path $PSScriptRoot 'expanded_basket_candidates.csv'),
  [string]$ManifestPath = (Join-Path $PSScriptRoot 'expanded_basket_manifest.csv'),
  [string]$SetDirectory = (Join-Path (Split-Path -Parent (Split-Path -Parent $PSScriptRoot)) 'Profiles\Tester')
)

$candidates = Import-Csv -LiteralPath $CandidateCsv
if ($candidates.Count -eq 0) {
  throw "No candidates found in $CandidateCsv"
}

if (-not (Test-Path -LiteralPath $SetDirectory)) {
  throw "Set directory not found: $SetDirectory"
}

$symbols = @(
  @{ Symbol = 'EURUSD'; Group = 'FX'; IsUs100 = $false; Segments = @(
    @{ Name = 'IS'; From = '2000.01.01'; To = '2012.01.01' },
    @{ Name = 'VAL'; From = '2012.01.01'; To = '2018.01.01' },
    @{ Name = 'OOS'; From = '2018.01.01'; To = '2026.05.31' }) },
  @{ Symbol = 'GBPUSD'; Group = 'FX'; IsUs100 = $false; Segments = @(
    @{ Name = 'IS'; From = '2000.01.01'; To = '2012.01.01' },
    @{ Name = 'VAL'; From = '2012.01.01'; To = '2018.01.01' },
    @{ Name = 'OOS'; From = '2018.01.01'; To = '2026.05.31' }) },
  @{ Symbol = 'USDJPY'; Group = 'FX'; IsUs100 = $false; Segments = @(
    @{ Name = 'IS'; From = '2000.01.01'; To = '2012.01.01' },
    @{ Name = 'VAL'; From = '2012.01.01'; To = '2018.01.01' },
    @{ Name = 'OOS'; From = '2018.01.01'; To = '2026.05.31' }) },
  @{ Symbol = 'EURJPY'; Group = 'FX'; IsUs100 = $false; Segments = @(
    @{ Name = 'IS'; From = '2000.01.01'; To = '2012.01.01' },
    @{ Name = 'VAL'; From = '2012.01.01'; To = '2018.01.01' },
    @{ Name = 'OOS'; From = '2018.01.01'; To = '2026.05.31' }) },
  @{ Symbol = 'XAUUSD'; Group = 'Metals'; IsUs100 = $false; Segments = @(
    @{ Name = 'IS'; From = '2006.04.01'; To = '2012.01.01' },
    @{ Name = 'VAL'; From = '2012.01.01'; To = '2018.01.01' },
    @{ Name = 'OOS'; From = '2018.01.01'; To = '2026.05.31' }) },
  @{ Symbol = 'XAGUSD'; Group = 'Metals'; IsUs100 = $false; Segments = @(
    @{ Name = 'IS'; From = '2006.04.01'; To = '2012.01.01' },
    @{ Name = 'VAL'; From = '2012.01.01'; To = '2018.01.01' },
    @{ Name = 'OOS'; From = '2018.01.01'; To = '2026.05.31' }) },
  @{ Symbol = 'US500'; Group = 'Indices'; IsUs100 = $false; Segments = @(
    @{ Name = 'IS'; From = '2005.01.01'; To = '2012.01.01' },
    @{ Name = 'VAL'; From = '2012.01.01'; To = '2018.01.01' },
    @{ Name = 'OOS'; From = '2018.01.01'; To = '2026.05.31' }) },
  @{ Symbol = 'US30'; Group = 'Indices'; IsUs100 = $false; Segments = @(
    @{ Name = 'IS'; From = '2005.01.01'; To = '2012.01.01' },
    @{ Name = 'VAL'; From = '2012.01.01'; To = '2018.01.01' },
    @{ Name = 'OOS'; From = '2018.01.01'; To = '2026.05.31' }) },
  @{ Symbol = 'US100'; Group = 'Indices'; IsUs100 = $true; Segments = @(
    @{ Name = 'VAL'; From = '2014.09.15'; To = '2018.01.01' },
    @{ Name = 'OOS'; From = '2018.01.01'; To = '2026.05.31' }) },
  @{ Symbol = 'UK100'; Group = 'Indices'; IsUs100 = $false; Segments = @(
    @{ Name = 'IS'; From = '2008.06.01'; To = '2012.01.01' },
    @{ Name = 'VAL'; From = '2012.01.01'; To = '2018.01.01' },
    @{ Name = 'OOS'; From = '2018.01.01'; To = '2026.05.31' }) },
  @{ Symbol = 'USOIL'; Group = 'Energy'; IsUs100 = $false; Segments = @(
    @{ Name = 'IS'; From = '2005.01.01'; To = '2012.01.01' },
    @{ Name = 'VAL'; From = '2012.01.01'; To = '2018.01.01' },
    @{ Name = 'OOS'; From = '2018.01.01'; To = '2026.05.31' }) },
  @{ Symbol = 'UKOIL'; Group = 'Energy'; IsUs100 = $false; Segments = @(
    @{ Name = 'IS'; From = '2005.04.01'; To = '2012.01.01' },
    @{ Name = 'VAL'; From = '2012.01.01'; To = '2018.01.01' },
    @{ Name = 'OOS'; From = '2018.01.01'; To = '2026.05.31' }) }
)

$manifest = New-Object System.Collections.Generic.List[object]
$testIndex = 1

foreach ($candidate in $candidates) {
  $manifoldId = "$($candidate.Run)_Pass$($candidate.Pass)"
  $setFile = "ImpulseContinuation_ExpandedBasket_$manifoldId.set"
  $setPath = Join-Path $SetDirectory $setFile

  @(
    "; Expanded basket fixed set from $manifoldId.",
    "; Generated by Files/WeekHighLow/New-ExpandedBasketBatch.ps1.",
    "g_HighLowPeriod=16408||16408||1||16408||N",
    "g_ATR_Period=14||14||1||14||N",
    "g_MinClusterSize=$($candidate.MinCluster)||$($candidate.MinCluster)||1||$($candidate.MinCluster)||N",
    "g_ATR_Cluster_multiplier=$($candidate.ClusterMult)||$($candidate.ClusterMult)||0.01||$($candidate.ClusterMult)||N",
    "g_ATR_StopLoss_multiplier=$($candidate.StopLossMult)||$($candidate.StopLossMult)||0.01||$($candidate.StopLossMult)||N",
    "g_impulse_lookback_hours=$($candidate.ImpulseLookback)||$($candidate.ImpulseLookback)||1||$($candidate.ImpulseLookback)||N",
    "g_pullback_lookforward_hours=$($candidate.PullbackLookforward)||$($candidate.PullbackLookforward)||1||$($candidate.PullbackLookforward)||N",
    "g_Impulse_ATR_multiplier=$($candidate.ImpulseMult)||$($candidate.ImpulseMult)||0.1||$($candidate.ImpulseMult)||N",
    "g_MinPullback_ATR_multiplier=$($candidate.PullbackMult)||$($candidate.PullbackMult)||0.1||$($candidate.PullbackMult)||N",
    "g_TakeProfitMultiplier=$($candidate.TP)||$($candidate.TP)||1||$($candidate.TP)||N",
    "g_Risk_Percentage=1.0||1.0||0.5||3.0||N",
    "g_EnableTradeCsvLogging=false||false||0||true||N",
    "g_TradeCsvManifoldId=$manifoldId",
    "g_TradeCsvTestId="
  ) | Set-Content -LiteralPath $setPath -Encoding ASCII

  foreach ($symbol in $symbols) {
    foreach ($segment in $symbol.Segments) {
      $dateLabel = ($segment.From -replace '\.', '') + '_' + ($segment.To -replace '\.', '')
      $report = "reports\expanded_basket\$($symbol.Symbol)_D1StopLossSplit_$($manifoldId)_$($segment.Name)_$dateLabel.xml"
      $testId = ('{0:D4}_{1}_{2}_{3}' -f $testIndex, $manifoldId, $symbol.Symbol, $segment.Name)

      $manifest.Add([pscustomobject]@{
        TestIndex = $testIndex
        TestId = $testId
        ManifoldId = $manifoldId
        Run = $candidate.Run
        Pass = $candidate.Pass
        Symbol = $symbol.Symbol
        MarketGroup = $symbol.Group
        Segment = $segment.Name
        FromDate = $segment.From
        ToDate = $segment.To
        SetFile = $setFile
        Report = $report
        ExpectedReport = "$report.htm"
        IsUS100 = $symbol.IsUs100
      })

      $testIndex++
    }
  }
}

$manifest | Export-Csv -LiteralPath $ManifestPath -NoTypeInformation -Encoding ASCII

Write-Host "Candidates: $($candidates.Count)"
Write-Host "Set files written: $($candidates.Count)"
Write-Host "Manifest tests: $($manifest.Count)"
Write-Host "Manifest: $ManifestPath"
