[Tester]
Expert=WeekHighLow\WeekHighLowEA.ex5
Symbol=AUDUSD
Period=H1

FromDate=2012.01.01
ToDate=2012.04.01

Model=4
Optimization=0
Visual=0

ExpertParameters=ImpulseContinuation_RollingManifold_Current.set
Report=reports\rolling_manifold\RM_2012Q2_STRICT_REUSE_OPT\validation\AUDUSD_RM_2012Q2_STRICT_REUSE_OPT_Pass1434_VALIDATION_20120101_20120401.xml

; ForwardMode=2
; OptimizationCriterion=7

ShutdownTerminal=1
