param(
  [string]$TerminalPath = 'C:\Program Files\MetaTrader 5\terminal64.exe',
  [int]$MaxRuntimeMinutes = 20,
  [int]$PollSeconds = 30,
  [int]$StartAtIndex = 1,
  [int]$MaxTests = 0,
  [switch]$RunExistingReports,
  [switch]$PrepareOnly,
  [bool]$EnableTradeCsvLogging = $true,
  [string[]]$Symbol = @(),
  [string[]]$Segment = @()
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Expand-FilterValues {
  param([string[]]$Values)

  @($Values | ForEach-Object {
    $_ -split ',' | ForEach-Object { $_.Trim() } | Where-Object { $_ }
  })
}

function Convert-ReportPathToFullPath {
  param(
    [string]$ReportRoot,
    [string]$ExpectedReport
  )

  $relative = $ExpectedReport -replace '/', '\'
  return Join-Path $ReportRoot $relative
}

function Set-InputLine {
  param(
    [System.Collections.Generic.List[string]]$Lines,
    [string]$Name,
    [string]$Value,
    [switch]$PlainString
  )

  $line = "$Name=$Value||$Value||0||$Value||N"
  if ($PlainString) {
    $line = "$Name=$Value"
  }

  for ($i = 0; $i -lt $Lines.Count; $i++) {
    if ($Lines[$i] -like "$Name=*") {
      $Lines[$i] = $line
      return
    }
  }

  $Lines.Add($line)
}

function Write-Pass2012SetFile {
  param([string]$SetPath)

  $lines = @(
    '; OANDA-EURXAU-P2012 fixed preset from OANDA EURUSD genetic pass 2012.',
    '; Generated by Run-OANDA-Pass2012-FX28-IsVal-20260623.ps1.',
    'g_HighLowPeriod=16408||16408||1||16408||N',
    'g_ATR_Period=14||14||1||14||N',
    'g_MinClusterSize=6||6||1||6||N',
    'g_ATR_Cluster_multiplier=0.4||0.4||0.01||0.4||N',
    'g_ATR_StopLoss_multiplier=0.3||0.3||0.01||0.3||N',
    'g_impulse_lookback_hours=24||24||1||24||N',
    'g_pullback_lookforward_hours=18||18||1||18||N',
    'g_Impulse_ATR_multiplier=0.6||0.6||0.1||0.6||N',
    'g_MinPullback_ATR_multiplier=0.4||0.4||0.1||0.4||N',
    'g_TakeProfitMultiplier=2||2||1||2||N',
    'g_Risk_Percentage=1.0||1.0||0.25||2.0||N',
    'g_EnableTradeCsvLogging=true||true||0||true||N',
    'g_TradeCsvManifoldId=OANDA_EURXAU_P2012_FX28_ISVAL',
    'g_TradeCsvTestId='
  )

  $lines | Set-Content -LiteralPath $SetPath -Encoding ASCII
}

function New-TestSetFile {
  param(
    [object]$Test,
    [string]$BaseSetPath,
    [string]$TempSetPath,
    [string]$TempSetFile
  )

  $lines = [System.Collections.Generic.List[string]]::new()
  foreach ($line in [System.IO.File]::ReadAllLines($BaseSetPath, [System.Text.Encoding]::ASCII)) {
    $lines.Add($line)
  }

  Set-InputLine -Lines $lines -Name 'g_EnableTradeCsvLogging' -Value 'true'
  Set-InputLine -Lines $lines -Name 'g_TradeCsvManifoldId' -Value 'OANDA_EURXAU_P2012_FX28_ISVAL' -PlainString
  Set-InputLine -Lines $lines -Name 'g_TradeCsvTestId' -Value $Test.TestId -PlainString

  [System.IO.File]::WriteAllLines($TempSetPath, $lines, [System.Text.Encoding]::ASCII)
  return $TempSetFile
}

function Append-Progress {
  param(
    [object]$Test,
    [string]$Status,
    [double]$DurationSeconds,
    [string]$ReportPath,
    [string]$Note
  )

  $row = [pscustomobject]@{
    Timestamp = (Get-Date).ToString('s')
    TestIndex = $Test.TestIndex
    TestId = $Test.TestId
    ManifoldId = $Test.ManifoldId
    Symbol = $Test.Symbol
    Segment = $Test.Segment
    FromDate = $Test.FromDate
    ToDate = $Test.ToDate
    Status = $Status
    DurationSeconds = [math]::Round($DurationSeconds, 2)
    ReportPath = $ReportPath
    Note = $Note
  }

  if (Test-Path -LiteralPath $ProgressPath) {
    $row | Export-Csv -LiteralPath $ProgressPath -NoTypeInformation -Append -Encoding ASCII
  } else {
    $row | Export-Csv -LiteralPath $ProgressPath -NoTypeInformation -Encoding ASCII
  }
}

$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$mql5Root = Split-Path -Parent (Split-Path -Parent $scriptRoot)
$terminalDataRoot = Split-Path -Parent $mql5Root
$reportRoot = $terminalDataRoot
$testerProfilesDir = Join-Path $mql5Root 'Profiles\Tester'
$experimentName = 'oanda_pass2012_fx28_isval_20260623'
$reportSubdir = "reports\$experimentName"
$reportDir = Join-Path $terminalDataRoot $reportSubdir
$ManifestPath = Join-Path $reportDir 'oanda_pass2012_fx28_isval_manifest.csv'
$ProgressPath = Join-Path $reportDir 'oanda_pass2012_fx28_isval_progress.csv'
$TempConfigPath = Join-Path $scriptRoot 'oanda_pass2012_fx28_isval_current.ini'
$BaseSetFile = 'ImpulseContinuation_OANDA_EURXAU_P2012_FX28_ISVAL.set'
$BaseSetPath = Join-Path $testerProfilesDir $BaseSetFile
$TempSetFile = 'ImpulseContinuation_OANDA_EURXAU_P2012_FX28_ISVAL_Current.set'
$TempSetPath = Join-Path $testerProfilesDir $TempSetFile
$TradeCsvPath = Join-Path $env:APPDATA 'MetaQuotes\Terminal\Common\Files\manifold_trades_OANDA_EURXAU_P2012_FX28_ISVAL.csv'

if (-not (Test-Path -LiteralPath $reportDir)) {
  New-Item -ItemType Directory -Path $reportDir -Force | Out-Null
}

Write-Pass2012SetFile -SetPath $BaseSetPath
Copy-Item -LiteralPath $BaseSetPath -Destination (Join-Path $reportDir $BaseSetFile) -Force
Copy-Item -LiteralPath $PSCommandPath -Destination (Join-Path $reportDir 'Run-OANDA-Pass2012-FX28-IsVal-20260623.ps1') -Force

$fxSymbols = @(
  'EURUSD', 'GBPUSD', 'USDJPY', 'USDCHF', 'USDCAD', 'AUDUSD', 'NZDUSD',
  'EURGBP', 'EURJPY', 'EURCHF', 'EURCAD', 'EURAUD', 'EURNZD',
  'GBPJPY', 'GBPCHF', 'GBPCAD', 'GBPAUD', 'GBPNZD',
  'CHFJPY', 'CADJPY', 'AUDJPY', 'NZDJPY',
  'CADCHF', 'AUDCHF', 'NZDCHF',
  'AUDCAD', 'NZDCAD', 'AUDNZD'
)

$segments = @(
  [pscustomobject]@{ Name = 'IS'; From = '2000.01.01'; To = '2012.01.01' },
  [pscustomobject]@{ Name = 'VAL'; From = '2012.01.01'; To = '2018.01.01' }
)

$manifestRows = New-Object System.Collections.Generic.List[object]
$testIndex = 1
foreach ($symbolName in $fxSymbols) {
  foreach ($segmentInfo in $segments) {
    $dateLabel = ($segmentInfo.From -replace '\.', '') + '_' + ($segmentInfo.To -replace '\.', '')
    $report = "$reportSubdir\$($symbolName)_D1StopLossSplit_OANDA_EURXAU_P2012_$($segmentInfo.Name)_$dateLabel.xml"
    $testId = ('{0:D3}_OANDA_EURXAU_P2012_{1}_{2}' -f $testIndex, $symbolName, $segmentInfo.Name)

    $manifestRows.Add([pscustomobject]@{
      TestIndex = $testIndex
      TestId = $testId
      ManifoldId = 'OANDA_EURXAU_P2012_FX28_ISVAL'
      Symbol = $symbolName
      MarketGroup = 'FX'
      Segment = $segmentInfo.Name
      FromDate = $segmentInfo.From
      ToDate = $segmentInfo.To
      SetFile = $BaseSetFile
      Report = $report
      ExpectedReport = "$report.htm"
    })

    $testIndex++
  }
}

$manifestRows | Export-Csv -LiteralPath $ManifestPath -NoTypeInformation -Encoding ASCII

Write-Host "Experiment directory: $reportDir"
Write-Host "Manifest: $ManifestPath"
Write-Host "Progress log: $ProgressPath"
Write-Host "Base set: $BaseSetPath"
Write-Host "Symbols: $($fxSymbols.Count)"
Write-Host "Segments: $($segments.Count)"
Write-Host "Manifest tests: $($manifestRows.Count)"
Write-Host "CSV logging during run: $([bool]$EnableTradeCsvLogging)"
Write-Host "Trade CSV: $TradeCsvPath"

if ($PrepareOnly) {
  Write-Host 'PrepareOnly set. No MT5 tests were run.'
  return
}

if (-not (Test-Path -LiteralPath $TerminalPath)) {
  throw "MT5 terminal not found: $TerminalPath"
}

$Symbol = @(Expand-FilterValues $Symbol)
$Segment = @(Expand-FilterValues $Segment)
$shouldRunExistingReports = [bool]$RunExistingReports -or [bool]$EnableTradeCsvLogging
if ($EnableTradeCsvLogging -and -not $RunExistingReports) {
  Write-Host 'CSV logging is enabled, so existing reports will be rerun to generate trade rows.'
}

$manifest = Import-Csv -LiteralPath $ManifestPath | Sort-Object { [int]$_.TestIndex }
if ($Symbol.Count -gt 0) {
  $manifest = @($manifest | Where-Object { $Symbol -contains $_.Symbol })
}
if ($Segment.Count -gt 0) {
  $manifest = @($manifest | Where-Object { $Segment -contains $_.Segment })
}
if ($manifest.Count -eq 0) {
  throw 'Manifest has no tests after filters.'
}

$completedStatuses = @('Completed', 'SkippedExistingReport')
$completedByProgress = @{}
if (Test-Path -LiteralPath $ProgressPath) {
  Import-Csv -LiteralPath $ProgressPath | ForEach-Object {
    if ($completedStatuses -contains $_.Status) {
      $completedByProgress[$_.TestId] = $true
    }
  }
}

$testsRunThisSession = 0
$overallStart = Get-Date

foreach ($test in $manifest) {
  $currentIndex = [int]$test.TestIndex
  if ($currentIndex -lt $StartAtIndex) {
    continue
  }
  if ($MaxTests -gt 0 -and $testsRunThisSession -ge $MaxTests) {
    break
  }

  $expectedReportPath = Convert-ReportPathToFullPath -ReportRoot $reportRoot -ExpectedReport $test.ExpectedReport
  if (-not $shouldRunExistingReports -and ($completedByProgress.ContainsKey($test.TestId) -or (Test-Path -LiteralPath $expectedReportPath))) {
    if (-not $completedByProgress.ContainsKey($test.TestId)) {
      Append-Progress -Test $test -Status 'SkippedExistingReport' -DurationSeconds 0 -ReportPath $expectedReportPath -Note 'Report already existed before run.'
    }
    continue
  }

  Write-Host ''
  Write-Host '====================================='
  Write-Host "Running $($test.TestIndex)/$($manifestRows.Count): $($test.TestId)"
  Write-Host "$($test.Symbol) $($test.Segment) $($test.FromDate) -> $($test.ToDate)"
  Write-Host '====================================='

  $expertParameters = $BaseSetFile
  if ($EnableTradeCsvLogging) {
    $expertParameters = New-TestSetFile -Test $test -BaseSetPath $BaseSetPath -TempSetPath $TempSetPath -TempSetFile $TempSetFile
  }

  $configContent = @(
    '[Tester]',
    'Expert=WeekHighLow\WeekHighLowEA.ex5',
    "Symbol=$($test.Symbol)",
    'Period=H1',
    '',
    "FromDate=$($test.FromDate)",
    "ToDate=$($test.ToDate)",
    '',
    'Model=4',
    'Optimization=0',
    'Visual=0',
    '',
    "ExpertParameters=$expertParameters",
    "Report=$($test.Report)",
    '',
    '; ForwardMode=2',
    '; OptimizationCriterion=7',
    '',
    'ShutdownTerminal=1'
  )

  $configContent | Set-Content -LiteralPath $TempConfigPath -Encoding ASCII

  $startTime = Get-Date
  $status = 'FailedNoReport'
  $note = ''
  $process = Start-Process -FilePath $TerminalPath -ArgumentList "/config:`"$TempConfigPath`"" -PassThru

  while (-not $process.HasExited) {
    Start-Sleep -Seconds $PollSeconds
    $process.Refresh()

    $elapsed = (Get-Date) - $startTime
    if ($elapsed.TotalMinutes -ge $MaxRuntimeMinutes) {
      $status = 'TimedOut'
      $note = "Timeout after $MaxRuntimeMinutes minutes."
      Stop-Process -Id $process.Id -Force -ErrorAction SilentlyContinue
      break
    }
  }

  Start-Sleep -Seconds 2
  $duration = ((Get-Date) - $startTime).TotalSeconds
  if (Test-Path -LiteralPath $expectedReportPath) {
    $status = 'Completed'
    if (-not $note) {
      $note = 'Report file found.'
    }
  } elseif (-not $note) {
    $note = 'MT5 exited but expected report was not found.'
  }

  Append-Progress -Test $test -Status $status -DurationSeconds $duration -ReportPath $expectedReportPath -Note $note
  $testsRunThisSession++

  Write-Host "Finished $($test.TestId): $status"
  Write-Host "Test duration: $([TimeSpan]::FromSeconds($duration).ToString())"
  Write-Host "Total elapsed: $(((Get-Date) - $overallStart).ToString())"
}

$overallDuration = (Get-Date) - $overallStart
Write-Host ''
Write-Host "Session complete. Tests run this session: $testsRunThisSession"
Write-Host "Overall duration: $($overallDuration.ToString())"
Write-Host "Progress log: $ProgressPath"
