param(
  [string]$TerminalPath = 'C:\Program Files\MetaTrader 5\terminal64.exe',
  [int]$MaxRuntimeMinutes = 45,
  [int]$PollSeconds = 30,
  [int]$StartAtIndex = 1,
  [int]$MaxTests = 0,
  [switch]$RunExistingReports,
  [switch]$PrepareOnly,
  [string[]]$PassId = @(),
  [string[]]$Symbol = @(),
  [string[]]$Segment = @()
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Expand-FilterValues {
  param([string[]]$Values)

  @($Values | ForEach-Object {
    $_ -split ',' | ForEach-Object { $_.Trim() } | Where-Object { $_ }
  })
}

function Convert-ReportPathToFullPath {
  param(
    [string]$ReportRoot,
    [string]$ExpectedReport
  )

  $relative = $ExpectedReport -replace '/', '\'
  return Join-Path $ReportRoot $relative
}

function Write-FixedSetFile {
  param(
    [object]$Pass,
    [string]$SetPath
  )

  $lines = @(
    "; OANDA EURUSD + XAUUSD same-manifold fixed preset from EURUSD genetic pass $($Pass.Pass).",
    '; Generated by Run-OANDA-EURUSD-XAUUSD-SameManifoldFixed-20260619.ps1.',
    'g_HighLowPeriod=16408||16408||1||16408||N',
    "g_ATR_Period=$($Pass.ATRPeriod)||$($Pass.ATRPeriod)||1||$($Pass.ATRPeriod)||N",
    "g_MinClusterSize=$($Pass.MinCluster)||$($Pass.MinCluster)||1||$($Pass.MinCluster)||N",
    "g_ATR_Cluster_multiplier=$($Pass.ClusterMult)||$($Pass.ClusterMult)||0.01||$($Pass.ClusterMult)||N",
    "g_ATR_StopLoss_multiplier=$($Pass.StopLossMult)||$($Pass.StopLossMult)||0.01||$($Pass.StopLossMult)||N",
    "g_impulse_lookback_hours=$($Pass.ImpulseLookback)||$($Pass.ImpulseLookback)||1||$($Pass.ImpulseLookback)||N",
    "g_pullback_lookforward_hours=$($Pass.PullbackLookforward)||$($Pass.PullbackLookforward)||1||$($Pass.PullbackLookforward)||N",
    "g_Impulse_ATR_multiplier=$($Pass.ImpulseMult)||$($Pass.ImpulseMult)||0.1||$($Pass.ImpulseMult)||N",
    "g_MinPullback_ATR_multiplier=$($Pass.PullbackMult)||$($Pass.PullbackMult)||0.1||$($Pass.PullbackMult)||N",
    "g_TakeProfitMultiplier=$($Pass.TP)||$($Pass.TP)||1||$($Pass.TP)||N",
    'g_Risk_Percentage=1.0||1.0||0.25||2.0||N',
    'g_EnableTradeCsvLogging=false||false||0||true||N',
    "g_TradeCsvManifoldId=OANDA_Pass$($Pass.Pass)",
    'g_TradeCsvTestId='
  )

  $lines | Set-Content -LiteralPath $SetPath -Encoding ASCII
}

function Append-Progress {
  param(
    [object]$Test,
    [string]$Status,
    [double]$DurationSeconds,
    [string]$ReportPath,
    [string]$Note
  )

  $row = [pscustomobject]@{
    Timestamp = (Get-Date).ToString('s')
    TestIndex = $Test.TestIndex
    TestId = $Test.TestId
    Pass = $Test.Pass
    Symbol = $Test.Symbol
    Segment = $Test.Segment
    FromDate = $Test.FromDate
    ToDate = $Test.ToDate
    Status = $Status
    DurationSeconds = [math]::Round($DurationSeconds, 2)
    ReportPath = $ReportPath
    Note = $Note
  }

  if (Test-Path -LiteralPath $ProgressPath) {
    $row | Export-Csv -LiteralPath $ProgressPath -NoTypeInformation -Append -Encoding ASCII
  } else {
    $row | Export-Csv -LiteralPath $ProgressPath -NoTypeInformation -Encoding ASCII
  }
}

$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$mql5Root = Split-Path -Parent (Split-Path -Parent $scriptRoot)
$terminalDataRoot = Split-Path -Parent $mql5Root
$reportRoot = $terminalDataRoot
$testerProfilesDir = Join-Path $mql5Root 'Profiles\Tester'
$reportDir = Join-Path $terminalDataRoot 'reports\oanda_eurusd_xauusd_same_manifold_20260619'
$ManifestPath = Join-Path $reportDir 'fixed_same_manifold_manifest.csv'
$ProgressPath = Join-Path $reportDir 'fixed_same_manifold_progress.csv'
$TempConfigPath = Join-Path $scriptRoot 'oanda_same_manifold_current.ini'

if (-not (Test-Path -LiteralPath $reportDir)) {
  New-Item -ItemType Directory -Path $reportDir -Force | Out-Null
}

$passes = @(
  [pscustomobject]@{ Pass = '2843'; ATRPeriod = '49'; MinCluster = '10'; ClusterMult = '0.4'; StopLossMult = '0.4'; ImpulseLookback = '48'; PullbackLookforward = '18'; ImpulseMult = '0.4'; PullbackMult = '0.4'; TP = '4' },
  [pscustomobject]@{ Pass = '2069'; ATRPeriod = '49'; MinCluster = '10'; ClusterMult = '0.4'; StopLossMult = '0.3'; ImpulseLookback = '72'; PullbackLookforward = '18'; ImpulseMult = '0.4'; PullbackMult = '0.4'; TP = '4' },
  [pscustomobject]@{ Pass = '4744'; ATRPeriod = '35'; MinCluster = '8'; ClusterMult = '0.4'; StopLossMult = '0.35'; ImpulseLookback = '120'; PullbackLookforward = '18'; ImpulseMult = '0.4'; PullbackMult = '0.6'; TP = '4' },
  [pscustomobject]@{ Pass = '533'; ATRPeriod = '14'; MinCluster = '5'; ClusterMult = '0.3'; StopLossMult = '0.4'; ImpulseLookback = '96'; PullbackLookforward = '24'; ImpulseMult = '0.4'; PullbackMult = '0.6'; TP = '3' },
  [pscustomobject]@{ Pass = '2551'; ATRPeriod = '28'; MinCluster = '8'; ClusterMult = '0.5'; StopLossMult = '0.3'; ImpulseLookback = '168'; PullbackLookforward = '18'; ImpulseMult = '1.0'; PullbackMult = '0.4'; TP = '2' },
  [pscustomobject]@{ Pass = '2012'; ATRPeriod = '14'; MinCluster = '6'; ClusterMult = '0.4'; StopLossMult = '0.3'; ImpulseLookback = '24'; PullbackLookforward = '18'; ImpulseMult = '0.6'; PullbackMult = '0.4'; TP = '2' }
)

foreach ($pass in $passes) {
  $setFile = "ImpulseContinuation_OANDA_SameManifold_Pass$($pass.Pass).set"
  $setPath = Join-Path $testerProfilesDir $setFile
  Write-FixedSetFile -Pass $pass -SetPath $setPath
  Copy-Item -LiteralPath $setPath -Destination (Join-Path $reportDir $setFile) -Force
  $pass | Add-Member -NotePropertyName SetFile -NotePropertyValue $setFile -Force
}

Copy-Item -LiteralPath $PSCommandPath -Destination (Join-Path $reportDir 'Run-OANDA-EURUSD-XAUUSD-SameManifoldFixed-20260619.ps1') -Force

$segmentsBySymbol = @{
  EURUSD = @(
    [pscustomobject]@{ Name = 'OOS'; From = '2018.01.01'; To = '2026.06.01' }
  )
  XAUUSD = @(
    [pscustomobject]@{ Name = 'IS'; From = '2000.01.01'; To = '2012.01.01' },
    [pscustomobject]@{ Name = 'VAL'; From = '2012.01.01'; To = '2018.01.01' },
    [pscustomobject]@{ Name = 'OOS'; From = '2018.01.01'; To = '2026.06.01' }
  )
}

$generatedManifest = New-Object System.Collections.Generic.List[object]
$testIndex = 1
foreach ($pass in $passes) {
  foreach ($symbolName in @('EURUSD', 'XAUUSD')) {
    foreach ($segmentInfo in $segmentsBySymbol[$symbolName]) {
      $dateLabel = ($segmentInfo.From -replace '\.', '') + '_' + ($segmentInfo.To -replace '\.', '')
      $report = "reports\oanda_eurusd_xauusd_same_manifold_20260619\$($symbolName)_D1StopLossSplit_OANDA_Pass$($pass.Pass)_$($segmentInfo.Name)_$dateLabel.xml"
      $testId = ('{0:D3}_Pass{1}_{2}_{3}' -f $testIndex, $pass.Pass, $symbolName, $segmentInfo.Name)

      $generatedManifest.Add([pscustomobject]@{
        TestIndex = $testIndex
        TestId = $testId
        Pass = $pass.Pass
        Symbol = $symbolName
        Segment = $segmentInfo.Name
        FromDate = $segmentInfo.From
        ToDate = $segmentInfo.To
        SetFile = $pass.SetFile
        Report = $report
        ExpectedReport = "$report.htm"
      })

      $testIndex++
    }
  }
}

$generatedManifest | Export-Csv -LiteralPath $ManifestPath -NoTypeInformation -Encoding ASCII

Write-Host "Report directory: $reportDir"
Write-Host "Manifest: $ManifestPath"
Write-Host "Progress log: $ProgressPath"
Write-Host "Manifest tests: $($generatedManifest.Count)"
Write-Host 'Generated fixed .set files in Profiles\Tester and copied snapshots into the report directory.'

if ($PrepareOnly) {
  Write-Host 'PrepareOnly set. No MT5 tests were run.'
  return
}

if (-not (Test-Path -LiteralPath $TerminalPath)) {
  throw "MT5 terminal not found: $TerminalPath"
}

$PassId = @(Expand-FilterValues $PassId)
$Symbol = @(Expand-FilterValues $Symbol)
$Segment = @(Expand-FilterValues $Segment)

$manifest = Import-Csv -LiteralPath $ManifestPath | Sort-Object { [int]$_.TestIndex }
if ($PassId.Count -gt 0) {
  $manifest = @($manifest | Where-Object { $PassId -contains $_.Pass })
}
if ($Symbol.Count -gt 0) {
  $manifest = @($manifest | Where-Object { $Symbol -contains $_.Symbol })
}
if ($Segment.Count -gt 0) {
  $manifest = @($manifest | Where-Object { $Segment -contains $_.Segment })
}
if ($manifest.Count -eq 0) {
  throw 'Manifest has no tests after filters.'
}

$completedStatuses = @('Completed', 'SkippedExistingReport')
$completedByProgress = @{}
if (Test-Path -LiteralPath $ProgressPath) {
  Import-Csv -LiteralPath $ProgressPath | ForEach-Object {
    if ($completedStatuses -contains $_.Status) {
      $completedByProgress[$_.TestId] = $true
    }
  }
}

$testsRunThisSession = 0
$overallStart = Get-Date

foreach ($test in $manifest) {
  $testIndex = [int]$test.TestIndex
  if ($testIndex -lt $StartAtIndex) {
    continue
  }

  if ($MaxTests -gt 0 -and $testsRunThisSession -ge $MaxTests) {
    break
  }

  $setPath = Join-Path $testerProfilesDir $test.SetFile
  if (-not (Test-Path -LiteralPath $setPath)) {
    throw "Set file not found: $setPath"
  }

  $expectedReportPath = Convert-ReportPathToFullPath -ReportRoot $reportRoot -ExpectedReport $test.ExpectedReport
  if (-not $RunExistingReports -and ($completedByProgress.ContainsKey($test.TestId) -or (Test-Path -LiteralPath $expectedReportPath))) {
    if (-not $completedByProgress.ContainsKey($test.TestId)) {
      Append-Progress -Test $test -Status 'SkippedExistingReport' -DurationSeconds 0 -ReportPath $expectedReportPath -Note 'Report already existed before run.'
    }
    continue
  }

  Write-Host ''
  Write-Host '====================================='
  Write-Host "Running $($test.TestIndex)/$($generatedManifest.Count): $($test.TestId)"
  Write-Host "$($test.Symbol) $($test.Segment) $($test.FromDate) -> $($test.ToDate)"
  Write-Host '====================================='

  $configContent = @(
    '[Tester]',
    'Expert=WeekHighLow\WeekHighLowEA.ex5',
    "Symbol=$($test.Symbol)",
    'Period=H1',
    '',
    "FromDate=$($test.FromDate)",
    "ToDate=$($test.ToDate)",
    '',
    'Model=4',
    'Optimization=0',
    'Visual=0',
    '',
    "ExpertParameters=$($test.SetFile)",
    "Report=$($test.Report)",
    '',
    '; ForwardMode=2',
    '; OptimizationCriterion=7',
    '',
    'ShutdownTerminal=1'
  )

  $configContent | Set-Content -LiteralPath $TempConfigPath -Encoding ASCII

  $startTime = Get-Date
  $status = 'FailedNoReport'
  $note = ''
  $process = Start-Process -FilePath $TerminalPath -ArgumentList "/config:`"$TempConfigPath`"" -PassThru

  while (-not $process.HasExited) {
    Start-Sleep -Seconds $PollSeconds
    $process.Refresh()

    $elapsed = (Get-Date) - $startTime
    if ($elapsed.TotalMinutes -ge $MaxRuntimeMinutes) {
      $status = 'TimedOut'
      $note = "Timeout after $MaxRuntimeMinutes minutes."
      Stop-Process -Id $process.Id -Force -ErrorAction SilentlyContinue
      break
    }
  }

  Start-Sleep -Seconds 2
  $duration = ((Get-Date) - $startTime).TotalSeconds
  if (Test-Path -LiteralPath $expectedReportPath) {
    $status = 'Completed'
    if (-not $note) {
      $note = 'Report file found.'
    }
  } elseif (-not $note) {
    $note = 'MT5 exited but expected report was not found.'
  }

  Append-Progress -Test $test -Status $status -DurationSeconds $duration -ReportPath $expectedReportPath -Note $note
  $testsRunThisSession++

  Write-Host "Finished $($test.TestId): $status"
  Write-Host "Test duration: $([TimeSpan]::FromSeconds($duration).ToString())"
  Write-Host "Total elapsed: $(((Get-Date) - $overallStart).ToString())"
}

$overallDuration = (Get-Date) - $overallStart
Write-Host ''
Write-Host "Session complete. Tests run this session: $testsRunThisSession"
Write-Host "Overall duration: $($overallDuration.ToString())"
Write-Host "Progress log: $ProgressPath"
